version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: db-produtos
    restart: always
    environment:
      POSTGRES_DB: produtos_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: .
    container_name: api-produtos
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
