spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/produtos_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
